package appli.frais;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 * Classe FenetreAccueil.
 * <p>
 * Cette classe représente la fenêtre principale de l'application de gestion des utilisateurs.
 * Elle étend {@link javax.swing.JFrame} et fournit une interface graphique pour :
 * <ul>
 *     <li>Afficher la liste des utilisateurs</li>
 *     <li>Ajouter, modifier et supprimer des utilisateurs</li>
 *     <li>Rechercher des utilisateurs par ID ou nom</li>
 *     <li>Gérer les champs de saisie et interactions avec la base de données</li>
 * </ul>
 * 
 * La classe utilise un objet {@link AccesBdD} pour interagir avec la base de données.
 * Elle contient un {@link javax.swing.JTable} pour afficher les utilisateurs
 * et des champs {@link javax.swing.JTextField} pour la saisie des informations.
 * 
 * Fonctionnalités principales :
 * <ul>
 *     <li>Initialisation de la fenêtre et des composants graphiques</li>
 *     <li>Chargement des utilisateurs depuis la base de données</li>
 *     <li>Gestion des actions sur les boutons Ajouter, Modifier, Vider, Supprimer</li>
 *     <li>Recherche d'utilisateurs avec tri</li>
 *     <li>Remplissage automatique des champs à partir de la sélection dans le tableau</li>
 * </ul>
 * 
 * Auteur : ebernard
 */

public class FenetreAccueil extends javax.swing.JFrame {
    private final AccesBdD bd;

    /**
     * Crée une nouvelle instance de FenetreAccueil.
     * <p>
     * Initialise la fenêtre, les composants graphiques, les listeners,
     * charge les utilisateurs depuis la base de données et configure la barre de recherche.
     * </p>
     */
    public FenetreAccueil() {
        this.bd = new AccesBdD();
        if (!Session.estConnecte() || !bd.estUtilisateurAuthentifie(Session.getLogin())) {
            JOptionPane.showMessageDialog(null, "Accès interdit : vous devez être authentifié !");
            System.exit(0);
        }

        initComponents();
        chargerUtilisateurs();

        initialiserSearchBar();
        initialiserTableClickListener();
        initialiserSelectionTable();
        initialiserBtnVider();
        initialiserBtnAjouter();
        initialiserBtnModifier();

        listerLesUtilisateurs();
        activerTriDecroissant(tableUtilisateurs);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupeRadio = new javax.swing.ButtonGroup();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        btnFermer = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUtilisateurs = new javax.swing.JTable();
        searchBar = new javax.swing.JTextField();
        radioId = new javax.swing.JRadioButton();
        radioNom = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelAjout = new javax.swing.JPanel();
        FieldId = new javax.swing.JTextField();
        FieldNom = new javax.swing.JTextField();
        FieldCp = new javax.swing.JTextField();
        FieldVille = new javax.swing.JTextField();
        FieldPrenom = new javax.swing.JTextField();
        FieldDate = new javax.swing.JTextField();
        FieldAddr = new javax.swing.JTextField();
        btnAjouter = new javax.swing.JButton();
        LabId = new javax.swing.JLabel();
        LabNom = new javax.swing.JLabel();
        LabAddr = new javax.swing.JLabel();
        LabCp = new javax.swing.JLabel();
        LabPrenom = new javax.swing.JLabel();
        LabDate = new javax.swing.JLabel();
        LabVille = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        TitreAjout = new javax.swing.JLabel();
        btnSupprimer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnVider = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frameAccueil"); // NOI18N

        jPanelHeader.setBackground(new java.awt.Color(0, 102, 153));

        jLabelTitre.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTitre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitre.setText("Gestion des Utilisateurs");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(jLabelTitre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelTitre)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        tableUtilisateurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "nom", "prenom", "login", "mdp", "adresse", "cp", "ville", "dateEmbauche"
            }
        ));
        JTableHeader header = tableUtilisateurs.getTableHeader();

        // Augmente la hauteur des lignes
        tableUtilisateurs.setRowHeight(25);

        // Augmente la hauteur de l'en-tête
        header.setPreferredSize(new Dimension(header.getPreferredSize().width, 30));

        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel label = (JLabel) super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

                label.setBackground(new Color(0, 102, 153)); // bleu
                label.setForeground(Color.WHITE);
                label.setFont(new Font("Segoe UI", Font.BOLD, 13));
                label.setHorizontalAlignment(JLabel.LEFT); // texte collé au bord gauche
                label.setBorder(BorderFactory.createEmptyBorder(0, 5, 0, 0)); // padding gauche
                label.setOpaque(true);

                return label;
            }
        });
        jScrollPane2.setViewportView(tableUtilisateurs);

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });

        GroupeRadio.add(radioId);
        radioId.setSelected(true);
        radioId.setText("ID");

        GroupeRadio.add(radioNom);
        radioNom.setText("NOM");
        radioNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNomActionPerformed(evt);
            }
        });

        jLabel1.setText("Rechercher par :");

        jPanelAjout.setBackground(new java.awt.Color(255, 255, 255));

        FieldId.setBackground(new java.awt.Color(244, 244, 244));

        FieldNom.setBackground(new java.awt.Color(244, 244, 244));

        FieldCp.setBackground(new java.awt.Color(244, 244, 244));

        FieldVille.setBackground(new java.awt.Color(244, 244, 244));

        FieldPrenom.setBackground(new java.awt.Color(244, 244, 244));

        FieldDate.setBackground(new java.awt.Color(244, 244, 244));

        FieldAddr.setBackground(new java.awt.Color(244, 244, 244));

        btnAjouter.setBackground(new java.awt.Color(0, 102, 153));
        btnAjouter.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouter.setText("Ajouter");

        LabId.setText("ID :");

        LabNom.setText("Nom :");

        LabAddr.setText("Adresse :");

        LabCp.setText("CP :");

        LabPrenom.setText("Prénom :");

        LabDate.setText("Date Embauche :");

        LabVille.setText("Ville :");

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        TitreAjout.setForeground(new java.awt.Color(255, 255, 255));
        TitreAjout.setText("Gestionnaire d'utilisateurs");
        TitreAjout.setPreferredSize(new java.awt.Dimension(136, 20));

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");

        btnVider.setText("Vider");
        btnVider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TitreAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVider, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitreAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimer)
                    .addComponent(btnModifier)
                    .addComponent(btnVider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelAjoutLayout = new javax.swing.GroupLayout(jPanelAjout);
        jPanelAjout.setLayout(jPanelAjoutLayout);
        jPanelAjoutLayout.setHorizontalGroup(
            jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjoutLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAjoutLayout.createSequentialGroup()
                        .addComponent(FieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAjoutLayout.createSequentialGroup()
                        .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabId)
                            .addComponent(LabCp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabVille)
                            .addComponent(FieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabDate)
                            .addComponent(FieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabPrenom))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabAddr)
                    .addComponent(FieldAddr)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addGap(80, 80, 80))
            .addGroup(jPanelAjoutLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelAjoutLayout.setVerticalGroup(
            jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjoutLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabId)
                        .addComponent(LabNom))
                    .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabAddr)
                        .addComponent(LabPrenom)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabDate)
                    .addComponent(LabVille)
                    .addComponent(LabCp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjouter))
                .addGap(16, 16, 16))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioId)
                                .addGap(18, 18, 18)
                                .addComponent(radioNom)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFermer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioId)
                                    .addComponent(radioNom)
                                    .addComponent(jLabel1)))
                            .addComponent(jPanelAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Initialise le comportement de la barre de recherche.
    * Gère le focus pour afficher ou masquer le texte par défaut.
    */
    private void initialiserSearchBar() {
        searchBar.setText("Recherche...");
        searchBar.setForeground(java.awt.Color.GRAY);

        searchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (searchBar.getText().equals("Recherche...")) {
                    searchBar.setText("");
                    searchBar.setForeground(java.awt.Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (searchBar.getText().isEmpty()) {
                    searchBar.setForeground(java.awt.Color.GRAY);
                    searchBar.setText("Recherche...");
                }
            }
        });
    }

    /**
    * Ajoute un écouteur de clic sur la table des utilisateurs.
    * Permet de remplir les champs du formulaire à partir de la ligne sélectionnée.
    */
    private void initialiserTableClickListener() {
        tableUtilisateurs.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                remplirChampsDepuisTable();
            }
        });
    }

    /**
    * Ajoute un écouteur de sélection sur la table des utilisateurs.
    * Met à jour les champs du formulaire avec les données de la ligne sélectionnée.
    */
    private void initialiserSelectionTable() {
        tableUtilisateurs.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = tableUtilisateurs.getSelectedRow();
                if (selectedRow != -1) {
                    FieldId.setText(tableUtilisateurs.getValueAt(selectedRow, 0).toString());
                    FieldNom.setText(tableUtilisateurs.getValueAt(selectedRow, 1).toString());
                    FieldPrenom.setText(tableUtilisateurs.getValueAt(selectedRow, 2).toString());
                    FieldAddr.setText(tableUtilisateurs.getValueAt(selectedRow, 5).toString());
                    FieldCp.setText(tableUtilisateurs.getValueAt(selectedRow, 6).toString());
                    FieldVille.setText(tableUtilisateurs.getValueAt(selectedRow, 7).toString());
                    FieldDate.setText(tableUtilisateurs.getValueAt(selectedRow, 8).toString());
                }
            }
        });
    }

    /**
    * Initialise le bouton "Vider" pour réinitialiser tous les champs du formulaire.
    */
    private void initialiserBtnVider() {
        btnVider.addActionListener(e -> viderChamps());
    }

    /**
    * Initialise le bouton "Ajouter" pour créer un nouvel utilisateur.
    * Vérifie les données, génère login et mot de passe, puis insère en base.
    */
    private void initialiserBtnAjouter() {
        btnAjouter.addActionListener((var e) -> {
            String id = FieldId.getText().trim();
            String nom = FieldNom.getText().trim();
            String prenom = FieldPrenom.getText().trim();
            String adresse = FieldAddr.getText().trim();
            String cp = FieldCp.getText().trim();
            String ville = FieldVille.getText().trim();
            String dateStr = FieldDate.getText().trim();

            if (id.isEmpty() || nom.isEmpty() || prenom.isEmpty() || adresse.isEmpty() ||
                cp.isEmpty() || ville.isEmpty() || dateStr.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tous les champs doivent être remplis !");
                return;
            }

            if (!estDateValide(dateStr)) {
                JOptionPane.showMessageDialog(null, "Format de date invalide. Utilise yyyy-MM-dd.");
                return;
            }

            Date dateEmbauche = Date.valueOf(dateStr);
            
            if (!cp.matches("\\d{5}")) {
                JOptionPane.showMessageDialog(null, "Le code postal doit contenir exactement 5 chiffres.");
                return;
            }

            if (nom.length() < 2 || prenom.length() < 2) {
                JOptionPane.showMessageDialog(null, "Nom et prénom doivent contenir au moins 2 caractères.");
                return;
            }

            if (dateEmbauche.after(Date.valueOf(LocalDate.now()))) {
                JOptionPane.showMessageDialog(null, "La date d'embauche ne peut pas être dans le futur.");
                return;
            }
            
            if (!nom.matches("[a-zA-ZÀ-ÿ\\- ]+")) {
                JOptionPane.showMessageDialog(null, "Le nom ne doit contenir que des lettres, des tirets ou des espaces.");
                return;
            }

            String login;
            try {
                login = bd.genererLoginUnique(nom, prenom);
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String mdp = bd.genererMotDePasse();

            if (bd.utilisateurExiste(nom, prenom, adresse, cp, ville, dateEmbauche)) {
                JOptionPane.showMessageDialog(null, "Cet utilisateur existe déjà !");
                return;
            }

            if (bd.loginExiste(login)) {
                JOptionPane.showMessageDialog(null, "Ce login existe déjà !");
                return;
            }

            int confirmation = JOptionPane.showConfirmDialog(
                null,
                "Confirmer l'ajout de l'utilisateur :\nNom : " + nom + "\nPrénom : " + prenom +
                "\nLogin : " + login + "\nMot de passe : " + mdp,
                "Confirmation",
                JOptionPane.YES_NO_OPTION
            );

            if (confirmation == JOptionPane.YES_OPTION) {
                try {
                    bd.ajoutUtilisateurs(id, nom, prenom, login, mdp, adresse, cp, ville, dateEmbauche);
                    chargerUtilisateurs();
                    JOptionPane.showMessageDialog(null, "Utilisateur ajouté !");
                    viderChamps();
                } catch (HeadlessException ex) {
                    Logger.getLogger(getClass().getName()).log(Level.SEVERE, "Erreur lors de l'ajout de l'utilisateur", ex);
                    JOptionPane.showMessageDialog(null, "Une erreur est survenue lors de l'ajout.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ajout annulé.");
            }
        });
    }


    /**
    * Initialise le bouton "Modifier" pour mettre à jour un utilisateur existant.
    * Gère la vérification, confirmation et mise à jour dans la base de données.
    */
    private void initialiserBtnModifier() {
        btnModifier.addActionListener((ActionEvent e) -> {
            int ligneSelectionnee = tableUtilisateurs.getSelectedRow();
            if (ligneSelectionnee == -1) {
                JOptionPane.showMessageDialog(null, "Sélectionne une ligne à modifier.");
                return;
            }

            String id = FieldId.getText().trim();
            String nom = FieldNom.getText().trim();
            String prenom = FieldPrenom.getText().trim();
            String adresse = FieldAddr.getText().trim();
            String cp = FieldCp.getText().trim();
            String ville = FieldVille.getText().trim();
            String dateStr = FieldDate.getText().trim();

            // Vérifications de base
            if (id.isEmpty() || nom.isEmpty() || prenom.isEmpty() || adresse.isEmpty() ||
                cp.isEmpty() || ville.isEmpty() || dateStr.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tous les champs doivent être remplis !");
                return;
            }

            if (!estDateValide(dateStr)) {
                JOptionPane.showMessageDialog(null, "Format de date invalide. Utilise yyyy-MM-dd.");
                return;
            }

            Date dateEmbauche = Date.valueOf(dateStr);

            if (!cp.matches("\\d{5}")) {
                JOptionPane.showMessageDialog(null, "Le code postal doit contenir exactement 5 chiffres.");
                return;
            }

            if (nom.length() < 2 || prenom.length() < 2) {
                JOptionPane.showMessageDialog(null, "Nom et prénom doivent contenir au moins 2 caractères.");
                return;
            }

            if (dateEmbauche.after(Date.valueOf(LocalDate.now()))) {
                JOptionPane.showMessageDialog(null, "La date d'embauche ne peut pas être dans le futur.");
                return;
            }

            if (!nom.matches("[a-zA-ZÀ-ÿ\\- ]+")) {
                JOptionPane.showMessageDialog(null, "Le nom ne doit contenir que des lettres, des tirets ou des espaces.");
                return;
            }

            String ancienNom = tableUtilisateurs.getValueAt(ligneSelectionnee, 1).toString();
            String ancienPrenom = tableUtilisateurs.getValueAt(ligneSelectionnee, 2).toString();
            String ancienLogin = tableUtilisateurs.getValueAt(ligneSelectionnee, 3).toString();
            String ancienneAdresse = tableUtilisateurs.getValueAt(ligneSelectionnee, 5).toString();
            String ancienCp = tableUtilisateurs.getValueAt(ligneSelectionnee, 6).toString();
            String ancienneVille = tableUtilisateurs.getValueAt(ligneSelectionnee, 7).toString();
            String ancienneDateStr = tableUtilisateurs.getValueAt(ligneSelectionnee, 8).toString();


            if (!estDateValide(ancienneDateStr)) {
                JOptionPane.showMessageDialog(null, "La date existante est invalide dans la table : " + ancienneDateStr);
                return;
            }

            Date ancienneDate = Date.valueOf(ancienneDateStr);

            boolean aucuneModification =
                nom.equals(ancienNom) &&
                prenom.equals(ancienPrenom) &&
                adresse.equals(ancienneAdresse) &&
                cp.equals(ancienCp) &&
                ville.equals(ancienneVille) &&
                dateEmbauche.equals(ancienneDate);

            if (aucuneModification) {
                JOptionPane.showMessageDialog(null, "Aucune modification détectée.");
                return;
            }

            String login = (!nom.equals(ancienNom) || !prenom.equals(ancienPrenom))
                ? bd.genererLoginUnique(nom, prenom)
                : ancienLogin;

            int confirmation = JOptionPane.showConfirmDialog(
                null,
                "Confirmer la modification de l'utilisateur :\nNom : " + nom + "\nPrénom : " + prenom + "\nLogin : " + login,
                "Confirmation",
                JOptionPane.YES_NO_OPTION
            );

            if (confirmation == JOptionPane.YES_OPTION) {
                try {
                    bd.modifUtilisateur(id, nom, prenom, login, adresse, cp, ville, dateEmbauche);
                    JOptionPane.showMessageDialog(null, "Utilisateur modifié !");
                    chargerUtilisateurs();
                    viderChamps();
                } catch (HeadlessException ex) {
                    Logger.getLogger(getClass().getName()).log(Level.SEVERE, "Erreur lors de la modification", ex);
                    JOptionPane.showMessageDialog(null, "Une erreur est survenue lors de la modification.", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Modification annulée.");
            }
        });
    }
   
    /**
    * Vérifie si une chaîne de caractères représente une date valide au format {@code yyyy-MM-dd}.
    * <p>
    * Cette méthode utilise {@link java.time.LocalDate#parse} avec un {@link java.time.format.DateTimeFormatter}
    * pour s'assurer que la date est bien conforme au format attendu.
    *
    * @param dateStr La chaîne représentant la date à valider
    * @return {@code true} si la chaîne est une date valide au format {@code yyyy-MM-dd}, {@code false} sinon
    */  
    private boolean estDateValide(String dateStr) {
        try {
            LocalDate.parse(dateStr, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            return true;
        } catch (DateTimeParseException e) {
            return false;
        }
    }
    
    /**
    * Vider tous les champs de saisie de la fenêtre.
    */
    private void viderChamps() {
        FieldId.setText("");
        FieldNom.setText("");
        FieldPrenom.setText("");
        FieldAddr.setText("");
        FieldCp.setText("");
        FieldVille.setText("");
        FieldDate.setText("");
    }
    
    /**
    * Remplit les champs de saisie avec les données de la ligne sélectionnée dans le tableau.
    * <p>
    * Si aucune ligne n'est sélectionnée, affiche un message d'erreur.
    * </p>
    */
    private void remplirChampsDepuisTable() {
        int ligne = tableUtilisateurs.getSelectedRow();
        if (ligne == -1) {
            JOptionPane.showMessageDialog(null, "Aucune ligne sélectionnée.");
            return;
        }

        FieldId.setText(tableUtilisateurs.getValueAt(ligne, 0).toString());
        FieldNom.setText(tableUtilisateurs.getValueAt(ligne, 1).toString());
        FieldPrenom.setText(tableUtilisateurs.getValueAt(ligne, 2).toString());
        FieldAddr.setText(tableUtilisateurs.getValueAt(ligne, 5).toString());
        FieldCp.setText(tableUtilisateurs.getValueAt(ligne, 6).toString());
        FieldVille.setText(tableUtilisateurs.getValueAt(ligne, 7).toString());
        FieldDate.setText(tableUtilisateurs.getValueAt(ligne, 8).toString());
    }

    /**
    * Charge tous les utilisateurs depuis la base de données et les affiche dans le tableau.
    * <p>
    * Utilise la méthode {@link AccesBdD#getLesUtilisateurs()}.
    * En cas d'erreur SQL, affiche un message d'erreur.
    * </p>
    */
    private void chargerUtilisateurs() {
        DefaultTableModel model = (DefaultTableModel) tableUtilisateurs.getModel();
        model.setRowCount(0);

        try {
            ResultSet rs = bd.getLesUtilisateurs();
            while (rs.next()) {
                Object[] ligne = new Object[] {
                    rs.getString("id"),
                    rs.getString("nom"),
                    rs.getString("prenom"),
                    rs.getString("login"),
                    rs.getString("mdp"),
                    rs.getString("adresse"),
                    rs.getString("cp"),
                    rs.getString("ville"),
                    rs.getString("dateEmbauche")
                };
                model.addRow(ligne);
            }
        } catch (SQLException e) {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, "Erreur lors du chargement des utilisateurs", e);
            JOptionPane.showMessageDialog(null, "Erreur lors du chargement des utilisateurs.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Gère l'action lors de la saisie dans la barre de recherche.
     * <p>
     * Recherche les utilisateurs selon le critère sélectionné (ID ou Nom)
     * et met à jour le tableau en conséquence.
     * </p>
     *
     * @param evt l'événement déclenché par la barre de recherche
     */
    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        String recherche = searchBar.getText().trim().toLowerCase();

        if (recherche.equals("recherche...")) {
            recherche = "";
        }

        DefaultTableModel tableModel = (DefaultTableModel) tableUtilisateurs.getModel();
        tableModel.setRowCount(0);

        if (recherche.isEmpty()) {
            listerLesUtilisateurs();
            return;
        }

        try (ResultSet rs = radioNom.isSelected() 
                            ? bd.getLesUtilisateursUnNom(recherche)
                            : radioId.isSelected() 
                                ? bd.getLesUtilisateursUnId(recherche)
                                : null) {

            if (rs == null) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner un critère de recherche.");
                return;
            }

            while (rs.next()) {
                Object[] utilisateur = {
                    rs.getString("id"),
                    rs.getString("nom"),
                    rs.getString("prenom"),
                    rs.getString("login"),
                    rs.getString("mdp"),
                    rs.getString("adresse"),
                    rs.getString("cp"),
                    rs.getString("ville"),
                    rs.getDate("dateEmbauche")
                };
                tableModel.addRow(utilisateur);
            }

            if (tableModel.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Aucun utilisateur trouvé pour \"" + recherche + "\".");
            }

        } catch (SQLException ex) {
            Logger.getLogger(FenetreAccueil.class.getName()).log(Level.SEVERE, "Erreur lors de la recherche d'utilisateur", ex);
            JOptionPane.showMessageDialog(this, "Erreur lors de la recherche en base de données.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }

        tableUtilisateurs.setModel(tableModel);
    }//GEN-LAST:event_searchBarActionPerformed
    
    /**
     * Action exécutée lors du clic sur le bouton "Fermer".
     * <p>
     * Met fin à l'exécution de l'application.
     * </p>
     *
     * @param evt l'événement déclenché par le clic sur le bouton
     */
    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnFermerActionPerformed

    private void radioNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNomActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViderActionPerformed

    /**
    * Liste tous les utilisateurs et les affiche dans le tableau.
    * <p>
    * Similaire à {@link #chargerUtilisateurs()}, mais peut être utilisé pour
    * actualiser la liste après une opération de modification ou ajout.
    * </p>
    */
    public final void listerLesUtilisateurs() {
        try {
            ResultSet rs = bd.getLesUtilisateurs();
            DefaultTableModel tableModel = (DefaultTableModel) tableUtilisateurs.getModel();

            tableModel.setRowCount(0);

            while (rs.next()) {
                Object[] utilisateur = new Object[9];
                utilisateur[0] = rs.getString("id");
                utilisateur[1] = rs.getString("nom");
                utilisateur[2] = rs.getString("prenom");
                utilisateur[3] = rs.getString("login");
                utilisateur[4] = rs.getString("mdp");
                utilisateur[5] = rs.getString("adresse");
                utilisateur[6] = rs.getString("cp");
                utilisateur[7] = rs.getString("ville");
                utilisateur[8] = rs.getDate("dateEmbauche"); 
                tableModel.addRow(utilisateur);
            }

            tableUtilisateurs.setModel(tableModel);

        } catch (SQLException ex) {
            Logger.getLogger(FenetreAccueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
    * Active le tri décroissant sur toutes les colonnes d'un tableau.
    * <p>
    * Permet de trier les données affichées par colonne.
    * </p>
    *
    * @param table le {@link JTable} sur lequel activer le tri
    */
    public final void activerTriDecroissant(JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        table.setRowSorter(sorter);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldAddr;
    private javax.swing.JTextField FieldCp;
    private javax.swing.JTextField FieldDate;
    private javax.swing.JTextField FieldId;
    private javax.swing.JTextField FieldNom;
    private javax.swing.JTextField FieldPrenom;
    private javax.swing.JTextField FieldVille;
    private javax.swing.ButtonGroup GroupeRadio;
    private javax.swing.JLabel LabAddr;
    private javax.swing.JLabel LabCp;
    private javax.swing.JLabel LabDate;
    private javax.swing.JLabel LabId;
    private javax.swing.JLabel LabNom;
    private javax.swing.JLabel LabPrenom;
    private javax.swing.JLabel LabVille;
    private javax.swing.JLabel TitreAjout;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JToggleButton btnFermer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnVider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAjout;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioId;
    private javax.swing.JRadioButton radioNom;
    private javax.swing.JTextField searchBar;
    private javax.swing.JTable tableUtilisateurs;
    // End of variables declaration//GEN-END:variables
}
